### PR TITLE
Add curriemace2009

### PR DESCRIPTION
**Pull request by CHIELDOnline**
Add curriemace2009 from HedvigS	Hedvig Skirgård	Wed Aug 15 2018 10:56:10 GMT+0200 (Central European Summer Time)

### CODE REVIEW

**Comment by HedvigS** [comment]
Might have done this all wrong, first attempt. When I get the hang of it I'll submit more.

**Comment by HedvigS** [comment]
I just noticed that there was also "language area", which actually fit better than "geographic spread". I couldn't push to the repos, and it didn't work editing the data through the web interface.

It's no biggie, but just thought I'd perfect it.

**Comment by seannyD** [comment]
No problem. It's now in the repository, and you can edit directly from github with a fork/pull or go to the document page on CHIELD and click "edit" (prob easier). [https://chield.excd.org/document.html?key=curriemace2009](https://chield.excd.org/document.html?key=curriemace2009)
You may have a point that "geographic spread" and "language area" are essentially the same thing and could be merged ...

**Comment by HedvigS** [comment]
I tried both, and it didn't work. Sorry. Pushing gives "You may not have permission to access the repository or the repository may have been archived" and editing on the website gives "There may be an error with the submission, please check data and try again."

Probably my fault somehow, I'm probs doing something unknown wrong somewhere.

**Comment by seannyD** [comment]
I just tried editing the document through the CHIELD website, and it seems to work.  Maybe try again?  Otherwise, you could download the csv and just send me the updated version.

**Comment by HedvigS** [comment]
I tried both things again, no luck :(.
Email csv

**Comment by HedvigS** [comment]
Ok, that's no good. I'll figure out what's going on.
Using Excel has been giving me troubles, so when I do need to look at something manually nowadays I use libreoffice. I didn't resave it in any new format though or specify anything new about text field delim or sep, but perhaps merely opening it with libreoffice did something. I'm sorry about that.

**Comment by HedvigS** [comment]
Looking at the file, I also had trouble with col alignment for reasons related to semi-colons. I edited it now. I couldn't find the definite point where the trouble had occurred :(
I still can't make a pull request directly to CHIELD as HedvigS through the Github dekstop client. I can on other reposes, I just tested Grambank to see if it works.
Is it possible for me to be added as a "contributor" to this repos? I promise to behave.

**Pull request merged**
